# Generated by Django 6.0 on 2025-12-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerprofile',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=10),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='price',
            field=models.IntegerField(default=0, help_text='Стоимость часа работы в RUB'),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='specialization',
            field=models.CharField(choices=[('wedding', 'Свадьба'), ('portrait', 'Портрет'), ('reportage', 'Репортаж'), ('lovestory', 'Love Story'), ('fashion', 'Fashion')], default='wedding', max_length=50),
        ),
    ]
