# Generated by Django 6.0 on 2025-12-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_photographerprofile_views_count_bookingrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
