# Generated by Django 6.0 on 2025-12-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_clientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='is_deleted_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='is_deleted_by_photographer',
            field=models.BooleanField(default=False),
        ),
    ]
