# Generated by Django 6.0 on 2025-12-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_bookingrequest_is_deleted_by_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='social_telegram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram (username)'),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='social_vk',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на ВКонтакте'),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Личный сайт'),
        ),
    ]
