# Generated by Django 6.0 on 2026-01-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_supportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('wedding', 'Свадьба'), ('portrait', 'Портрет'), ('reportage', 'Репортаж'), ('lovestory', 'Love Story'), ('fashion', 'Fashion')], default='wedding', max_length=50, verbose_name='Категория'),
        ),
    ]
