# Generated by Django 6.0 on 2026-01-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_supportrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='admin_response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ администратора'),
        ),
    ]
